#### general settings
name: SDSD_indoor
use_tb_logger: true
model: video_base6_5
distortion: sr
scale: 1
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: sdsd_indoor
    mode: video_samesize
    interval_list: [1]
    random_reverse: false
    border_mode: false
    dataroot_GT: /mnt/proj73/xgxu/proj3_code/EDVR/datasets/indoor_np/GT
    dataroot_LQ: /mnt/proj73/xgxu/proj3_code/EDVR/datasets/indoor_np/input
    train_size: [960, 512]
    cache_keys: ~
    cache_data: true
    padding: new_info
    testing_dir: pair13,pair21,pair23,pair31,pair33,pair15

    N_frames: 5     # how many frames as a input.
    use_shuffle: true
    n_workers: 3  # per GPU
    batch_size: 16
    GT_size: 256     # size you want to crop out as input sample.
    LQ_size: 256
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: sdsd_indoor
    mode: video_samesize1
    dataroot_GT: /mnt/proj73/xgxu/proj3_code/EDVR/datasets/indoor_np/GT
    dataroot_LQ: /mnt/proj73/xgxu/proj3_code/EDVR/datasets/indoor_np/input
    cache_data: true
    N_frames: 5
    padding: new_info
    train_size: [960, 512]
    testing_dir: pair13,pair21,pair23,pair31,pair33,pair15

#### network structures
network_G:
  which_model_G: DP3DF
  nf: 64
  nframes: 5      # must be same as N_frames in dataset.
  groups: 8
  front_RBs: 5
  back_RBs: 10
  predeblur: true     # default false
  HR_in: true       # true if size(input) == size(HR)
  w_TSA: true

#### path
path:
  root: /mnt/proj73/xgxu/DP3DF
  # pretrain_model_G: null
  strict_load: false
  # resume_state: null

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 4e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 600000
  ft_tsa_only: 0
  warmup_iter: -1  # -1: no warm up
  T_period: [50000, 100000, 150000, 150000, 150000]
  restarts: [50000, 150000, 300000, 450000]
  restart_weights: [1, 1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: cb
  pixel_weight: 1.0
  val_freq: !!float 3e3

  manual.resize960x512_seed: 0

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5000
